//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctrlSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ctrlSucursal()
        {
            this.ctrlUsuario = new HashSet<ctrlUsuario>();
        }
    
        public int Id { get; set; }
        public string Sucursal { get; set; }
        public string Direccion { get; set; }
        public string LugarExpedicion { get; set; }
        public string Telefono { get; set; }
        public int CveAlmacen { get; set; }
        public string Almacen { get; set; }
        public string SerieFactura { get; set; }
        public string SerieNCredito { get; set; }
        public string SerieNDescuento { get; set; }
        public string SeriePago { get; set; }
        public bool SNActivo { get; set; }
        public bool SNPenalizacion { get; set; }
        public Nullable<int> Penalizacion { get; set; }
        public string Leyenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctrlUsuario> ctrlUsuario { get; set; }
    }
}
